version: "3.3"
services:
  api:
    build: 
      context: .
    stdin_open: true
    tty: true
    env_file:
      - .env
    depends_on:
      - mongo
    volumes:
      - .:/code
    ports:
      - "3013:3013"
  mongo:
      image: mongo
      env_file:
        - .env
      environment:
        - MONGO_INITDB_ROOT_USERNAME
        - MONGO_INITDB_ROOT_PASSWORD
        - MONGO_INITDB_DATABASE
 
      ports:
        - 27000:27017
      volumes:
        - ./db.init.js:/docker-entrypoint-initdb.d/init.js:ro