apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  clusterIP: None # Since replicasets connect to particular pods (with identitites: statefulset)
  selector:
    app: mongo 
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017 
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  labels: 
    app: mongo
spec:
  replicas: 1
  serviceName: mongo-service
  selector:
    matchLabels:
      app: mongo
  volumeClaimTemplates:
  - metadata:
      name: mongo-persistance-storage-claim
    spec:
      storageClassName: "standard" # default for minikubes
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 100Mi
  template: 
    metadata:
      labels:
        app: mongo
    spec:
      terminationGracePeriodSeconds: 15
      initContainers:
      - name: copy-key
        image: busybox
        command: 
          - /bin/sh
          - "-c"
          - |
            cp /shared-secrets/key /shared-secrets-data/key;
            chown 999:999 /shared-secrets-data/key;
            chmod 400 /shared-secrets-data/key;
        volumeMounts:
        - name: mongo-shared-key
          mountPath: "/shared-secrets"
        - name: mongo-shared-key-data
          mountPath: "/shared-secrets-data"
      containers:
      - name: mongo-container
        image: mongo
        ports:
        - containerPort: 27017
        envFrom:
        - configMapRef:
            name: config
        - secretRef:
            name: secret
        volumeMounts:
        - name: init-scripts
          mountPath: "/docker-entrypoint-initdb.d/"
        - name: mongo-shared-key-data
          mountPath: "/shared-secrets"
          readOnly: true
        - name: mongo-persistance-storage-claim
          mountPath: /data/db
        args: [
          "--replSet", 
          "$(MONGO_REPLICA_SET_NAME)", 
          "--bind_ip",
          "0.0.0.0", 
          "--keyFile",  
          "/shared-secrets/key",
          "--setParameter",
          "authenticationMechanisms=SCRAM-SHA-1"
        ]

      volumes:
      - name: init-scripts
        configMap:
          name: db-init
      - name: mongo-shared-key-data
        emptyDir: {}
      - name: mongo-shared-key
        secret:
          secretName: mongo-key-secret
          defaultMode: 0400
